### ISSUE TITLE
Invalid call to RecyclerView on MediaGridAdapter

### ISSUE THREAD

**Issue by aldoborrero** [butterproject/butter-android#149]
I leave here the stacktrace to see what was happening

```03-28 18:29:50.011 3373-3373/? W/RecyclerView: Cannot call this method in a scroll callback. Scroll callbacks might be run during a measure & layout pass where you cannot change the RecyclerView data. Any method call that might change the structure of the RecyclerView or the adapter contents should be postponed to the next frame.
                                               java.lang.IllegalStateException: 
                                                   at android.support.v7.widget.RecyclerView.assertNotInLayoutOrScroll(RecyclerView.java:2536)
                                                   at android.support.v7.widget.RecyclerView$RecyclerViewDataObserver.onChanged(RecyclerView.java:4886)
                                                   at android.support.v7.widget.RecyclerView$AdapterDataObservable.notifyChanged(RecyclerView.java:11101)
                                                   at android.support.v7.widget.RecyclerView$Adapter.notifyDataSetChanged(RecyclerView.java:6590)
                                                   at butter.droid.adapters.MediaGridAdapter.addLoading_aroundBody2(MediaGridAdapter.java:161)
                                                   at butter.droid.adapters.MediaGridAdapter$AjcClosure3.run(MediaGridAdapter.java:1)
                                                   at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                   at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                   at butter.droid.adapters.MediaGridAdapter.addLoading(MediaGridAdapter.java:154)
                                                   at butter.droid.fragments.MediaListFragment$2.run(MediaListFragment.java:278)
                                                   at butter.droid.base.utils.ThreadUtils.runOnUiThread(ThreadUtils.java:33)
                                                   at butter.droid.fragments.MediaListFragment.updateUI(MediaListFragment.java:236)
                                                   at butter.droid.fragments.MediaListFragment.setState_aroundBody0(MediaListFragment.java:296)
                                                   at butter.droid.fragments.MediaListFragment$AjcClosure1.run(MediaListFragment.java:1)
                                                   at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
                                                   at hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
                                                   at butter.droid.fragments.MediaListFragment.setState(MediaListFragment.java:294)
                                                   at butter.droid.fragments.MediaListFragment.access$800(MediaListFragment.java:76)
                                                   at butter.droid.fragments.MediaListFragment$6.onScrolled(MediaListFragment.java:490)
                                                   at android.support.v7.widget.RecyclerView.dispatchOnScrolled(RecyclerView.java:4572)
                                                   at android.support.v7.widget.RecyclerView.dispatchLayoutStep3(RecyclerView.java:3633)
                                                   at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3277)
                                                   at android.support.v7.widget.RecyclerView.onLayout(RecyclerView.java:3798)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.support.v4.view.ViewPager.onLayout(ViewPager.java:1795)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
                                                   at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
                                                   at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                                   at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.support.design.widget.HeaderScrollingViewBehavior.layoutChild(HeaderScrollingViewBehavior.java:131)
                                                   at android.support.design.widget.ViewOffsetBehavior.onLayoutChild(ViewOffsetBehavior.java:42)
                                                   at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onLayoutChild(AppBarLayout.java:1375)
                                                   at android.support.design.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:870)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.support.v4.widget.DrawerLayout.onLayout(DrawerLayout.java:1193)
                                                   at android.view.View.layout(View.java:14817)
                                                   at android.view.ViewGroup.layout(ViewGroup.java:4631)
                                                   at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
                                               	at android.widget.FrameLayo
03-28 18:29:50.011 3373-3373/? V/MediaGridAdapter: ⇠ addLoading [4ms]
03-28 18:29:50.011 3373-3373/? V/MediaListFragment: ⇠ setState [5ms]
03-28 18:29:50.015 3373-3403/? V/MediaListFragment: ⇢ onSuccess(filters=butter.droid.base.providers.media.MediaProvider$Filters@528fe248, items=[butter.droid.base.providers.media.models.Movie@5294d248, butter.droid.base.providers.media.models.Movie@5294da18, butter.droid.base.providers.media.models.Movie@5294dc0c, butter.droid.base.providers.media.models.Movie@5294ddf0, butter.droid.base.providers.media.models.Movie@5294dff8, butter.droid.base.providers.media.models.Movie@5294e1dc, butter.droid.base.providers.media.models.Movie@5294e3f0, butter.droid.base.providers.media.models.Movie@5294e5b8, butter.droid.base.providers.media.models.Movie@5294e76c, butter.droid.base.providers.media.models.Movie@5294e944, butter.droid.base.providers.media.models.Movie@5294eae8, butter.droid.base.providers.media.models.Movie@5294ecdc, butter.droid.base.providers.media.models.Movie@5294eec4, butter.droid.base.providers.media.models.Movie@5294f0b0], changed=true) [Thread:"OkHttp http://butter.vodo.net/..."]
03-28 18:29:50.015 3373-3403/? V/MediaListFragment: ⇢ setState(state=LOADED) [Thread:"OkHttp http://butter.vodo.net/..."]
03-28 18:29:50.015 3373-3403/? V/MediaListFragment: ⇠ setState [0ms]
03-28 18:29:50.015 3373-3403/? V/MediaListFragment: ⇠ onSuccess [0ms]
03-28 18:29:50.167 3373-3373/? V/MediaGridAdapter: ⇢ isLoading()
03-28 18:29:50.167 3373-3373/? V/MediaGridAdapter: ⇠ isLoading [0ms] = true
03-28 18:29:50.167 3373-3373/? V/MediaGridAdapter: ⇢ removeLoading()
03-28 18:29:50.167 3373-3373/? V/MediaGridAdapter: ⇠ removeLoading [0ms]```

**Comment by blazsolar** [comment]
this is irrelevant. Adapters were rewritten already.
